using System;
using Rocket.Surgery.Blazor.FontAwesome6;
namespace Rocket.Surgery.Blazor.FontAwesome6.Pro;
public static partial class FaBrands
{
   private static Icon? _42Groupf;
   public static Icon _42Group => _42Groupf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "42-group");
   public static Icon Innosoft => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands._42Group;
   private static Icon? _500pxf;
   public static Icon _500px => _500pxf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "500px");
   private static Icon? AccessibleIconf;
   public static Icon AccessibleIcon => AccessibleIconf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "accessible-icon");
   private static Icon? Accusoftf;
   public static Icon Accusoft => Accusoftf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "accusoft");
   private static Icon? Adnf;
   public static Icon Adn => Adnf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "adn");
   private static Icon? Adversalf;
   public static Icon Adversal => Adversalf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "adversal");
   private static Icon? Affiliatethemef;
   public static Icon Affiliatetheme => Affiliatethemef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "affiliatetheme");
   private static Icon? Airbnbf;
   public static Icon Airbnb => Airbnbf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "airbnb");
   private static Icon? Algoliaf;
   public static Icon Algolia => Algoliaf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "algolia");
   private static Icon? Alipayf;
   public static Icon Alipay => Alipayf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "alipay");
   private static Icon? Amazonf;
   public static Icon Amazon => Amazonf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "amazon");
   private static Icon? AmazonPayf;
   public static Icon AmazonPay => AmazonPayf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "amazon-pay");
   private static Icon? Amiliaf;
   public static Icon Amilia => Amiliaf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "amilia");
   private static Icon? Androidf;
   public static Icon Android => Androidf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "android");
   private static Icon? Angellistf;
   public static Icon Angellist => Angellistf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "angellist");
   private static Icon? Angrycreativef;
   public static Icon Angrycreative => Angrycreativef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "angrycreative");
   private static Icon? Angularf;
   public static Icon Angular => Angularf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "angular");
   private static Icon? AppStoref;
   public static Icon AppStore => AppStoref ??= new Icon(IconFamily.Classic, IconStyle.Brands, "app-store");
   private static Icon? AppStoreIosf;
   public static Icon AppStoreIos => AppStoreIosf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "app-store-ios");
   private static Icon? Apperf;
   public static Icon Apper => Apperf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "apper");
   private static Icon? Applef;
   public static Icon Apple => Applef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "apple");
   private static Icon? ApplePayf;
   public static Icon ApplePay => ApplePayf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "apple-pay");
   private static Icon? Artstationf;
   public static Icon Artstation => Artstationf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "artstation");
   private static Icon? Asymmetrikf;
   public static Icon Asymmetrik => Asymmetrikf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "asymmetrik");
   private static Icon? Atlassianf;
   public static Icon Atlassian => Atlassianf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "atlassian");
   private static Icon? Audiblef;
   public static Icon Audible => Audiblef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "audible");
   private static Icon? Autoprefixerf;
   public static Icon Autoprefixer => Autoprefixerf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "autoprefixer");
   private static Icon? Avianexf;
   public static Icon Avianex => Avianexf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "avianex");
   private static Icon? Aviatof;
   public static Icon Aviato => Aviatof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "aviato");
   private static Icon? Awsf;
   public static Icon Aws => Awsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "aws");
   private static Icon? Bandcampf;
   public static Icon Bandcamp => Bandcampf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "bandcamp");
   private static Icon? BattleNetf;
   public static Icon BattleNet => BattleNetf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "battle-net");
   private static Icon? Behancef;
   public static Icon Behance => Behancef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "behance");
   private static Icon? Bilibilif;
   public static Icon Bilibili => Bilibilif ??= new Icon(IconFamily.Classic, IconStyle.Brands, "bilibili");
   private static Icon? Bimobjectf;
   public static Icon Bimobject => Bimobjectf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "bimobject");
   private static Icon? Bitbucketf;
   public static Icon Bitbucket => Bitbucketf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "bitbucket");
   private static Icon? Bitcoinf;
   public static Icon Bitcoin => Bitcoinf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "bitcoin");
   private static Icon? Bityf;
   public static Icon Bity => Bityf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "bity");
   private static Icon? BlackTief;
   public static Icon BlackTie => BlackTief ??= new Icon(IconFamily.Classic, IconStyle.Brands, "black-tie");
   private static Icon? Blackberryf;
   public static Icon Blackberry => Blackberryf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "blackberry");
   private static Icon? Bloggerf;
   public static Icon Blogger => Bloggerf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "blogger");
   private static Icon? BloggerBf;
   public static Icon BloggerB => BloggerBf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "blogger-b");
   private static Icon? Bluetoothf;
   public static Icon Bluetooth => Bluetoothf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "bluetooth");
   private static Icon? BluetoothBf;
   public static Icon BluetoothB => BluetoothBf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "bluetooth-b");
   private static Icon? Bootstrapf;
   public static Icon Bootstrap => Bootstrapf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "bootstrap");
   private static Icon? Botsf;
   public static Icon Bots => Botsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "bots");
   private static Icon? Bravef;
   public static Icon Brave => Bravef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "brave");
   private static Icon? BraveReversef;
   public static Icon BraveReverse => BraveReversef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "brave-reverse");
   private static Icon? Btcf;
   public static Icon Btc => Btcf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "btc");
   private static Icon? Bufferf;
   public static Icon Buffer => Bufferf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "buffer");
   private static Icon? Buromobelexpertef;
   public static Icon Buromobelexperte => Buromobelexpertef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "buromobelexperte");
   private static Icon? BuyNLargef;
   public static Icon BuyNLarge => BuyNLargef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "buy-n-large");
   private static Icon? Buyselladsf;
   public static Icon Buysellads => Buyselladsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "buysellads");
   private static Icon? CanadianMapleLeaff;
   public static Icon CanadianMapleLeaf => CanadianMapleLeaff ??= new Icon(IconFamily.Classic, IconStyle.Brands, "canadian-maple-leaf");
   private static Icon? CcAmazonPayf;
   public static Icon CcAmazonPay => CcAmazonPayf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cc-amazon-pay");
   private static Icon? CcAmexf;
   public static Icon CcAmex => CcAmexf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cc-amex");
   private static Icon? CcApplePayf;
   public static Icon CcApplePay => CcApplePayf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cc-apple-pay");
   private static Icon? CcDinersClubf;
   public static Icon CcDinersClub => CcDinersClubf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cc-diners-club");
   private static Icon? CcDiscoverf;
   public static Icon CcDiscover => CcDiscoverf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cc-discover");
   private static Icon? CcJcbf;
   public static Icon CcJcb => CcJcbf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cc-jcb");
   private static Icon? CcMastercardf;
   public static Icon CcMastercard => CcMastercardf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cc-mastercard");
   private static Icon? CcPaypalf;
   public static Icon CcPaypal => CcPaypalf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cc-paypal");
   private static Icon? CcStripef;
   public static Icon CcStripe => CcStripef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cc-stripe");
   private static Icon? CcVisaf;
   public static Icon CcVisa => CcVisaf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cc-visa");
   private static Icon? Centercodef;
   public static Icon Centercode => Centercodef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "centercode");
   private static Icon? Centosf;
   public static Icon Centos => Centosf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "centos");
   private static Icon? Chromef;
   public static Icon Chrome => Chromef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "chrome");
   private static Icon? Chromecastf;
   public static Icon Chromecast => Chromecastf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "chromecast");
   private static Icon? Cloudflaref;
   public static Icon Cloudflare => Cloudflaref ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cloudflare");
   private static Icon? Cloudscalef;
   public static Icon Cloudscale => Cloudscalef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cloudscale");
   private static Icon? Cloudsmithf;
   public static Icon Cloudsmith => Cloudsmithf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cloudsmith");
   private static Icon? Cloudversifyf;
   public static Icon Cloudversify => Cloudversifyf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cloudversify");
   private static Icon? Cmplidf;
   public static Icon Cmplid => Cmplidf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cmplid");
   private static Icon? Codepenf;
   public static Icon Codepen => Codepenf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "codepen");
   private static Icon? Codiepief;
   public static Icon Codiepie => Codiepief ??= new Icon(IconFamily.Classic, IconStyle.Brands, "codiepie");
   private static Icon? Confluencef;
   public static Icon Confluence => Confluencef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "confluence");
   private static Icon? Connectdevelopf;
   public static Icon Connectdevelop => Connectdevelopf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "connectdevelop");
   private static Icon? Contaof;
   public static Icon Contao => Contaof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "contao");
   private static Icon? CottonBureauf;
   public static Icon CottonBureau => CottonBureauf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cotton-bureau");
   private static Icon? Cpanelf;
   public static Icon Cpanel => Cpanelf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cpanel");
   private static Icon? CreativeCommonsf;
   public static Icon CreativeCommons => CreativeCommonsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons");
   private static Icon? CreativeCommonsByf;
   public static Icon CreativeCommonsBy => CreativeCommonsByf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-by");
   private static Icon? CreativeCommonsNcf;
   public static Icon CreativeCommonsNc => CreativeCommonsNcf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-nc");
   private static Icon? CreativeCommonsNcEuf;
   public static Icon CreativeCommonsNcEu => CreativeCommonsNcEuf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-nc-eu");
   private static Icon? CreativeCommonsNcJpf;
   public static Icon CreativeCommonsNcJp => CreativeCommonsNcJpf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-nc-jp");
   private static Icon? CreativeCommonsNdf;
   public static Icon CreativeCommonsNd => CreativeCommonsNdf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-nd");
   private static Icon? CreativeCommonsPdf;
   public static Icon CreativeCommonsPd => CreativeCommonsPdf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-pd");
   private static Icon? CreativeCommonsPdAltf;
   public static Icon CreativeCommonsPdAlt => CreativeCommonsPdAltf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-pd-alt");
   private static Icon? CreativeCommonsRemixf;
   public static Icon CreativeCommonsRemix => CreativeCommonsRemixf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-remix");
   private static Icon? CreativeCommonsSaf;
   public static Icon CreativeCommonsSa => CreativeCommonsSaf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-sa");
   private static Icon? CreativeCommonsSamplingf;
   public static Icon CreativeCommonsSampling => CreativeCommonsSamplingf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-sampling");
   private static Icon? CreativeCommonsSamplingPlusf;
   public static Icon CreativeCommonsSamplingPlus => CreativeCommonsSamplingPlusf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-sampling-plus");
   private static Icon? CreativeCommonsSharef;
   public static Icon CreativeCommonsShare => CreativeCommonsSharef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-share");
   private static Icon? CreativeCommonsZerof;
   public static Icon CreativeCommonsZero => CreativeCommonsZerof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "creative-commons-zero");
   private static Icon? CriticalRolef;
   public static Icon CriticalRole => CriticalRolef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "critical-role");
   private static Icon? Css3f;
   public static Icon Css3 => Css3f ??= new Icon(IconFamily.Classic, IconStyle.Brands, "css3");
   private static Icon? Css3Altf;
   public static Icon Css3Alt => Css3Altf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "css3-alt");
   private static Icon? Cuttlefishf;
   public static Icon Cuttlefish => Cuttlefishf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "cuttlefish");
   private static Icon? DAndDf;
   public static Icon DAndD => DAndDf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "d-and-d");
   private static Icon? DAndDBeyondf;
   public static Icon DAndDBeyond => DAndDBeyondf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "d-and-d-beyond");
   private static Icon? Dailymotionf;
   public static Icon Dailymotion => Dailymotionf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "dailymotion");
   private static Icon? Dashcubef;
   public static Icon Dashcube => Dashcubef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "dashcube");
   private static Icon? Debianf;
   public static Icon Debian => Debianf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "debian");
   private static Icon? Deezerf;
   public static Icon Deezer => Deezerf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "deezer");
   private static Icon? Deliciousf;
   public static Icon Delicious => Deliciousf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "delicious");
   private static Icon? Deploydogf;
   public static Icon Deploydog => Deploydogf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "deploydog");
   private static Icon? Deskprof;
   public static Icon Deskpro => Deskprof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "deskpro");
   private static Icon? Devf;
   public static Icon Dev => Devf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "dev");
   private static Icon? Deviantartf;
   public static Icon Deviantart => Deviantartf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "deviantart");
   private static Icon? Dhlf;
   public static Icon Dhl => Dhlf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "dhl");
   private static Icon? Diasporaf;
   public static Icon Diaspora => Diasporaf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "diaspora");
   private static Icon? Diggf;
   public static Icon Digg => Diggf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "digg");
   private static Icon? DigitalOceanf;
   public static Icon DigitalOcean => DigitalOceanf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "digital-ocean");
   private static Icon? Discordf;
   public static Icon Discord => Discordf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "discord");
   private static Icon? Discoursef;
   public static Icon Discourse => Discoursef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "discourse");
   private static Icon? Dochubf;
   public static Icon Dochub => Dochubf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "dochub");
   private static Icon? Dockerf;
   public static Icon Docker => Dockerf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "docker");
   private static Icon? Draft2digitalf;
   public static Icon Draft2digital => Draft2digitalf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "draft2digital");
   private static Icon? Dribbblef;
   public static Icon Dribbble => Dribbblef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "dribbble");
   private static Icon? Dropboxf;
   public static Icon Dropbox => Dropboxf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "dropbox");
   private static Icon? Drupalf;
   public static Icon Drupal => Drupalf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "drupal");
   private static Icon? Dyalogf;
   public static Icon Dyalog => Dyalogf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "dyalog");
   private static Icon? Earlybirdsf;
   public static Icon Earlybirds => Earlybirdsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "earlybirds");
   private static Icon? Ebayf;
   public static Icon Ebay => Ebayf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "ebay");
   private static Icon? Edgef;
   public static Icon Edge => Edgef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "edge");
   private static Icon? EdgeLegacyf;
   public static Icon EdgeLegacy => EdgeLegacyf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "edge-legacy");
   private static Icon? Elementorf;
   public static Icon Elementor => Elementorf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "elementor");
   private static Icon? Ellof;
   public static Icon Ello => Ellof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "ello");
   private static Icon? Emberf;
   public static Icon Ember => Emberf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "ember");
   private static Icon? Empiref;
   public static Icon Empire => Empiref ??= new Icon(IconFamily.Classic, IconStyle.Brands, "empire");
   private static Icon? Enviraf;
   public static Icon Envira => Enviraf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "envira");
   private static Icon? Erlangf;
   public static Icon Erlang => Erlangf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "erlang");
   private static Icon? Ethereumf;
   public static Icon Ethereum => Ethereumf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "ethereum");
   private static Icon? Etsyf;
   public static Icon Etsy => Etsyf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "etsy");
   private static Icon? Evernotef;
   public static Icon Evernote => Evernotef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "evernote");
   private static Icon? Expeditedsslf;
   public static Icon Expeditedssl => Expeditedsslf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "expeditedssl");
   private static Icon? Facebookf;
   public static Icon Facebook => Facebookf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "facebook");
   private static Icon? FacebookFf;
   public static Icon FacebookF => FacebookFf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "facebook-f");
   private static Icon? FacebookMessengerf;
   public static Icon FacebookMessenger => FacebookMessengerf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "facebook-messenger");
   private static Icon? FantasyFlightGamesf;
   public static Icon FantasyFlightGames => FantasyFlightGamesf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "fantasy-flight-games");
   private static Icon? Fedexf;
   public static Icon Fedex => Fedexf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "fedex");
   private static Icon? Fedoraf;
   public static Icon Fedora => Fedoraf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "fedora");
   private static Icon? Figmaf;
   public static Icon Figma => Figmaf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "figma");
   private static Icon? Firefoxf;
   public static Icon Firefox => Firefoxf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "firefox");
   private static Icon? FirefoxBrowserf;
   public static Icon FirefoxBrowser => FirefoxBrowserf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "firefox-browser");
   private static Icon? FirstOrderf;
   public static Icon FirstOrder => FirstOrderf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "first-order");
   private static Icon? FirstOrderAltf;
   public static Icon FirstOrderAlt => FirstOrderAltf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "first-order-alt");
   private static Icon? Firstdraftf;
   public static Icon Firstdraft => Firstdraftf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "firstdraft");
   private static Icon? Flickrf;
   public static Icon Flickr => Flickrf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "flickr");
   private static Icon? Flipboardf;
   public static Icon Flipboard => Flipboardf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "flipboard");
   private static Icon? Flyf;
   public static Icon Fly => Flyf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "fly");
   private static Icon? FontAwesomef;
   public static Icon FontAwesome => FontAwesomef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "font-awesome");
   public static Icon FontAwesomeFlag => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.FontAwesome;
   public static Icon FontAwesomeLogoFull => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.FontAwesome;
   private static Icon? Fonticonsf;
   public static Icon Fonticons => Fonticonsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "fonticons");
   private static Icon? FonticonsFif;
   public static Icon FonticonsFi => FonticonsFif ??= new Icon(IconFamily.Classic, IconStyle.Brands, "fonticons-fi");
   private static Icon? FortAwesomef;
   public static Icon FortAwesome => FortAwesomef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "fort-awesome");
   private static Icon? FortAwesomeAltf;
   public static Icon FortAwesomeAlt => FortAwesomeAltf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "fort-awesome-alt");
   private static Icon? Forumbeef;
   public static Icon Forumbee => Forumbeef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "forumbee");
   private static Icon? Foursquaref;
   public static Icon Foursquare => Foursquaref ??= new Icon(IconFamily.Classic, IconStyle.Brands, "foursquare");
   private static Icon? FreeCodeCampf;
   public static Icon FreeCodeCamp => FreeCodeCampf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "free-code-camp");
   private static Icon? Freebsdf;
   public static Icon Freebsd => Freebsdf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "freebsd");
   private static Icon? Fulcrumf;
   public static Icon Fulcrum => Fulcrumf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "fulcrum");
   private static Icon? GalacticRepublicf;
   public static Icon GalacticRepublic => GalacticRepublicf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "galactic-republic");
   private static Icon? GalacticSenatef;
   public static Icon GalacticSenate => GalacticSenatef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "galactic-senate");
   private static Icon? GetPocketf;
   public static Icon GetPocket => GetPocketf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "get-pocket");
   private static Icon? Ggf;
   public static Icon Gg => Ggf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "gg");
   private static Icon? GgCirclef;
   public static Icon GgCircle => GgCirclef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "gg-circle");
   private static Icon? Gitf;
   public static Icon Git => Gitf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "git");
   private static Icon? GitAltf;
   public static Icon GitAlt => GitAltf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "git-alt");
   private static Icon? Githubf;
   public static Icon Github => Githubf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "github");
   private static Icon? GithubAltf;
   public static Icon GithubAlt => GithubAltf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "github-alt");
   private static Icon? Gitkrakenf;
   public static Icon Gitkraken => Gitkrakenf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "gitkraken");
   private static Icon? Gitlabf;
   public static Icon Gitlab => Gitlabf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "gitlab");
   private static Icon? Gitterf;
   public static Icon Gitter => Gitterf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "gitter");
   private static Icon? Glidef;
   public static Icon Glide => Glidef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "glide");
   private static Icon? GlideGf;
   public static Icon GlideG => GlideGf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "glide-g");
   private static Icon? Goforef;
   public static Icon Gofore => Goforef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "gofore");
   private static Icon? Golangf;
   public static Icon Golang => Golangf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "golang");
   private static Icon? Goodreadsf;
   public static Icon Goodreads => Goodreadsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "goodreads");
   private static Icon? GoodreadsGf;
   public static Icon GoodreadsG => GoodreadsGf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "goodreads-g");
   private static Icon? Googlef;
   public static Icon Google => Googlef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "google");
   private static Icon? GoogleDrivef;
   public static Icon GoogleDrive => GoogleDrivef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "google-drive");
   private static Icon? GooglePayf;
   public static Icon GooglePay => GooglePayf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "google-pay");
   private static Icon? GooglePlayf;
   public static Icon GooglePlay => GooglePlayf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "google-play");
   private static Icon? GooglePlusf;
   public static Icon GooglePlus => GooglePlusf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "google-plus");
   private static Icon? GooglePlusGf;
   public static Icon GooglePlusG => GooglePlusGf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "google-plus-g");
   private static Icon? GoogleScholarf;
   public static Icon GoogleScholar => GoogleScholarf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "google-scholar");
   private static Icon? GoogleWalletf;
   public static Icon GoogleWallet => GoogleWalletf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "google-wallet");
   private static Icon? Gratipayf;
   public static Icon Gratipay => Gratipayf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "gratipay");
   private static Icon? Gravf;
   public static Icon Grav => Gravf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "grav");
   private static Icon? Gripfiref;
   public static Icon Gripfire => Gripfiref ??= new Icon(IconFamily.Classic, IconStyle.Brands, "gripfire");
   private static Icon? Gruntf;
   public static Icon Grunt => Gruntf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "grunt");
   private static Icon? Guildedf;
   public static Icon Guilded => Guildedf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "guilded");
   private static Icon? Gulpf;
   public static Icon Gulp => Gulpf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "gulp");
   private static Icon? HackerNewsf;
   public static Icon HackerNews => HackerNewsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "hacker-news");
   private static Icon? Hackerrankf;
   public static Icon Hackerrank => Hackerrankf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "hackerrank");
   private static Icon? Hashnodef;
   public static Icon Hashnode => Hashnodef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "hashnode");
   private static Icon? Hipsf;
   public static Icon Hips => Hipsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "hips");
   private static Icon? HireAHelperf;
   public static Icon HireAHelper => HireAHelperf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "hire-a-helper");
   private static Icon? Hivef;
   public static Icon Hive => Hivef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "hive");
   private static Icon? Hoolif;
   public static Icon Hooli => Hoolif ??= new Icon(IconFamily.Classic, IconStyle.Brands, "hooli");
   private static Icon? Hornbillf;
   public static Icon Hornbill => Hornbillf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "hornbill");
   private static Icon? Hotjarf;
   public static Icon Hotjar => Hotjarf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "hotjar");
   private static Icon? Houzzf;
   public static Icon Houzz => Houzzf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "houzz");
   private static Icon? Html5f;
   public static Icon Html5 => Html5f ??= new Icon(IconFamily.Classic, IconStyle.Brands, "html5");
   private static Icon? Hubspotf;
   public static Icon Hubspot => Hubspotf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "hubspot");
   private static Icon? Idealf;
   public static Icon Ideal => Idealf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "ideal");
   private static Icon? Imdbf;
   public static Icon Imdb => Imdbf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "imdb");
   private static Icon? Instagramf;
   public static Icon Instagram => Instagramf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "instagram");
   private static Icon? Instalodf;
   public static Icon Instalod => Instalodf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "instalod");
   private static Icon? Intercomf;
   public static Icon Intercom => Intercomf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "intercom");
   private static Icon? InternetExplorerf;
   public static Icon InternetExplorer => InternetExplorerf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "internet-explorer");
   private static Icon? Invisionf;
   public static Icon Invision => Invisionf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "invision");
   private static Icon? Ioxhostf;
   public static Icon Ioxhost => Ioxhostf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "ioxhost");
   private static Icon? ItchIof;
   public static Icon ItchIo => ItchIof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "itch-io");
   private static Icon? Itunesf;
   public static Icon Itunes => Itunesf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "itunes");
   private static Icon? ItunesNotef;
   public static Icon ItunesNote => ItunesNotef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "itunes-note");
   private static Icon? Javaf;
   public static Icon Java => Javaf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "java");
   private static Icon? JediOrderf;
   public static Icon JediOrder => JediOrderf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "jedi-order");
   private static Icon? Jenkinsf;
   public static Icon Jenkins => Jenkinsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "jenkins");
   private static Icon? Jiraf;
   public static Icon Jira => Jiraf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "jira");
   private static Icon? Jogetf;
   public static Icon Joget => Jogetf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "joget");
   private static Icon? Joomlaf;
   public static Icon Joomla => Joomlaf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "joomla");
   private static Icon? Jsf;
   public static Icon Js => Jsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "js");
   private static Icon? Jsfiddlef;
   public static Icon Jsfiddle => Jsfiddlef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "jsfiddle");
   private static Icon? Kagglef;
   public static Icon Kaggle => Kagglef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "kaggle");
   private static Icon? Keybasef;
   public static Icon Keybase => Keybasef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "keybase");
   private static Icon? Keycdnf;
   public static Icon Keycdn => Keycdnf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "keycdn");
   private static Icon? Kickstarterf;
   public static Icon Kickstarter => Kickstarterf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "kickstarter");
   private static Icon? KickstarterKf;
   public static Icon KickstarterK => KickstarterKf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "kickstarter-k");
   private static Icon? Korvuef;
   public static Icon Korvue => Korvuef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "korvue");
   private static Icon? Laravelf;
   public static Icon Laravel => Laravelf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "laravel");
   private static Icon? Lastfmf;
   public static Icon Lastfm => Lastfmf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "lastfm");
   private static Icon? Leanpubf;
   public static Icon Leanpub => Leanpubf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "leanpub");
   private static Icon? Lessf;
   public static Icon Less => Lessf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "less");
   private static Icon? Letterboxdf;
   public static Icon Letterboxd => Letterboxdf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "letterboxd");
   private static Icon? Linef;
   public static Icon Line => Linef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "line");
   private static Icon? Linkedinf;
   public static Icon Linkedin => Linkedinf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "linkedin");
   private static Icon? LinkedinInf;
   public static Icon LinkedinIn => LinkedinInf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "linkedin-in");
   private static Icon? Linodef;
   public static Icon Linode => Linodef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "linode");
   private static Icon? Linuxf;
   public static Icon Linux => Linuxf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "linux");
   private static Icon? Lyftf;
   public static Icon Lyft => Lyftf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "lyft");
   private static Icon? Magentof;
   public static Icon Magento => Magentof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "magento");
   private static Icon? Mailchimpf;
   public static Icon Mailchimp => Mailchimpf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "mailchimp");
   private static Icon? Mandalorianf;
   public static Icon Mandalorian => Mandalorianf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "mandalorian");
   private static Icon? Markdownf;
   public static Icon Markdown => Markdownf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "markdown");
   private static Icon? Mastodonf;
   public static Icon Mastodon => Mastodonf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "mastodon");
   private static Icon? Maxcdnf;
   public static Icon Maxcdn => Maxcdnf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "maxcdn");
   private static Icon? Mdbf;
   public static Icon Mdb => Mdbf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "mdb");
   private static Icon? Medappsf;
   public static Icon Medapps => Medappsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "medapps");
   private static Icon? Mediumf;
   public static Icon Medium => Mediumf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "medium");
   public static Icon MediumM => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.Medium;
   private static Icon? Medrtf;
   public static Icon Medrt => Medrtf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "medrt");
   private static Icon? Meetupf;
   public static Icon Meetup => Meetupf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "meetup");
   private static Icon? Megaportf;
   public static Icon Megaport => Megaportf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "megaport");
   private static Icon? Mendeleyf;
   public static Icon Mendeley => Mendeleyf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "mendeley");
   private static Icon? Metaf;
   public static Icon Meta => Metaf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "meta");
   private static Icon? Microblogf;
   public static Icon Microblog => Microblogf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "microblog");
   private static Icon? Microsoftf;
   public static Icon Microsoft => Microsoftf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "microsoft");
   private static Icon? Mintbitf;
   public static Icon Mintbit => Mintbitf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "mintbit");
   private static Icon? Mixf;
   public static Icon Mix => Mixf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "mix");
   private static Icon? Mixcloudf;
   public static Icon Mixcloud => Mixcloudf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "mixcloud");
   private static Icon? Mixerf;
   public static Icon Mixer => Mixerf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "mixer");
   private static Icon? Mizunif;
   public static Icon Mizuni => Mizunif ??= new Icon(IconFamily.Classic, IconStyle.Brands, "mizuni");
   private static Icon? Modxf;
   public static Icon Modx => Modxf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "modx");
   private static Icon? Monerof;
   public static Icon Monero => Monerof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "monero");
   private static Icon? Napsterf;
   public static Icon Napster => Napsterf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "napster");
   private static Icon? Neosf;
   public static Icon Neos => Neosf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "neos");
   private static Icon? NfcDirectionalf;
   public static Icon NfcDirectional => NfcDirectionalf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "nfc-directional");
   private static Icon? NfcSymbolf;
   public static Icon NfcSymbol => NfcSymbolf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "nfc-symbol");
   private static Icon? Nimblrf;
   public static Icon Nimblr => Nimblrf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "nimblr");
   private static Icon? Nodef;
   public static Icon Node => Nodef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "node");
   private static Icon? NodeJsf;
   public static Icon NodeJs => NodeJsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "node-js");
   private static Icon? Npmf;
   public static Icon Npm => Npmf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "npm");
   private static Icon? Ns8f;
   public static Icon Ns8 => Ns8f ??= new Icon(IconFamily.Classic, IconStyle.Brands, "ns8");
   private static Icon? Nutritionixf;
   public static Icon Nutritionix => Nutritionixf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "nutritionix");
   private static Icon? OctopusDeployf;
   public static Icon OctopusDeploy => OctopusDeployf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "octopus-deploy");
   private static Icon? Odnoklassnikif;
   public static Icon Odnoklassniki => Odnoklassnikif ??= new Icon(IconFamily.Classic, IconStyle.Brands, "odnoklassniki");
   private static Icon? Odyseef;
   public static Icon Odysee => Odyseef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "odysee");
   private static Icon? OldRepublicf;
   public static Icon OldRepublic => OldRepublicf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "old-republic");
   private static Icon? Opencartf;
   public static Icon Opencart => Opencartf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "opencart");
   private static Icon? Openidf;
   public static Icon Openid => Openidf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "openid");
   private static Icon? Opensusef;
   public static Icon Opensuse => Opensusef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "opensuse");
   private static Icon? Operaf;
   public static Icon Opera => Operaf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "opera");
   private static Icon? OptinMonsterf;
   public static Icon OptinMonster => OptinMonsterf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "optin-monster");
   private static Icon? Orcidf;
   public static Icon Orcid => Orcidf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "orcid");
   private static Icon? Osif;
   public static Icon Osi => Osif ??= new Icon(IconFamily.Classic, IconStyle.Brands, "osi");
   private static Icon? Padletf;
   public static Icon Padlet => Padletf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "padlet");
   private static Icon? Page4f;
   public static Icon Page4 => Page4f ??= new Icon(IconFamily.Classic, IconStyle.Brands, "page4");
   private static Icon? Pagelinesf;
   public static Icon Pagelines => Pagelinesf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "pagelines");
   private static Icon? Palfedf;
   public static Icon Palfed => Palfedf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "palfed");
   private static Icon? Patreonf;
   public static Icon Patreon => Patreonf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "patreon");
   private static Icon? Paypalf;
   public static Icon Paypal => Paypalf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "paypal");
   private static Icon? Perbytef;
   public static Icon Perbyte => Perbytef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "perbyte");
   private static Icon? Periscopef;
   public static Icon Periscope => Periscopef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "periscope");
   private static Icon? Phabricatorf;
   public static Icon Phabricator => Phabricatorf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "phabricator");
   private static Icon? PhoenixFrameworkf;
   public static Icon PhoenixFramework => PhoenixFrameworkf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "phoenix-framework");
   private static Icon? PhoenixSquadronf;
   public static Icon PhoenixSquadron => PhoenixSquadronf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "phoenix-squadron");
   private static Icon? Phpf;
   public static Icon Php => Phpf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "php");
   private static Icon? PiedPiperf;
   public static Icon PiedPiper => PiedPiperf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "pied-piper");
   private static Icon? PiedPiperAltf;
   public static Icon PiedPiperAlt => PiedPiperAltf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "pied-piper-alt");
   private static Icon? PiedPiperHatf;
   public static Icon PiedPiperHat => PiedPiperHatf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "pied-piper-hat");
   private static Icon? PiedPiperPpf;
   public static Icon PiedPiperPp => PiedPiperPpf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "pied-piper-pp");
   private static Icon? Pinterestf;
   public static Icon Pinterest => Pinterestf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "pinterest");
   private static Icon? PinterestPf;
   public static Icon PinterestP => PinterestPf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "pinterest-p");
   private static Icon? Pixf;
   public static Icon Pix => Pixf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "pix");
   private static Icon? Pixivf;
   public static Icon Pixiv => Pixivf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "pixiv");
   private static Icon? Playstationf;
   public static Icon Playstation => Playstationf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "playstation");
   private static Icon? ProductHuntf;
   public static Icon ProductHunt => ProductHuntf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "product-hunt");
   private static Icon? Pushedf;
   public static Icon Pushed => Pushedf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "pushed");
   private static Icon? Pythonf;
   public static Icon Python => Pythonf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "python");
   private static Icon? Qqf;
   public static Icon Qq => Qqf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "qq");
   private static Icon? Quinscapef;
   public static Icon Quinscape => Quinscapef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "quinscape");
   private static Icon? Quoraf;
   public static Icon Quora => Quoraf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "quora");
   private static Icon? RProjectf;
   public static Icon RProject => RProjectf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "r-project");
   private static Icon? RaspberryPif;
   public static Icon RaspberryPi => RaspberryPif ??= new Icon(IconFamily.Classic, IconStyle.Brands, "raspberry-pi");
   private static Icon? Ravelryf;
   public static Icon Ravelry => Ravelryf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "ravelry");
   private static Icon? Reactf;
   public static Icon React => Reactf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "react");
   private static Icon? Reacteuropef;
   public static Icon Reacteurope => Reacteuropef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "reacteurope");
   private static Icon? Readmef;
   public static Icon Readme => Readmef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "readme");
   private static Icon? Rebelf;
   public static Icon Rebel => Rebelf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "rebel");
   private static Icon? RedRiverf;
   public static Icon RedRiver => RedRiverf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "red-river");
   private static Icon? Redditf;
   public static Icon Reddit => Redditf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "reddit");
   private static Icon? RedditAlienf;
   public static Icon RedditAlien => RedditAlienf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "reddit-alien");
   private static Icon? Redhatf;
   public static Icon Redhat => Redhatf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "redhat");
   private static Icon? Renrenf;
   public static Icon Renren => Renrenf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "renren");
   private static Icon? Replydf;
   public static Icon Replyd => Replydf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "replyd");
   private static Icon? Researchgatef;
   public static Icon Researchgate => Researchgatef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "researchgate");
   private static Icon? Resolvingf;
   public static Icon Resolving => Resolvingf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "resolving");
   private static Icon? Revf;
   public static Icon Rev => Revf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "rev");
   private static Icon? Rocketchatf;
   public static Icon Rocketchat => Rocketchatf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "rocketchat");
   private static Icon? Rockrmsf;
   public static Icon Rockrms => Rockrmsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "rockrms");
   private static Icon? Rustf;
   public static Icon Rust => Rustf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "rust");
   private static Icon? Safarif;
   public static Icon Safari => Safarif ??= new Icon(IconFamily.Classic, IconStyle.Brands, "safari");
   private static Icon? Salesforcef;
   public static Icon Salesforce => Salesforcef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "salesforce");
   private static Icon? Sassf;
   public static Icon Sass => Sassf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "sass");
   private static Icon? Schlixf;
   public static Icon Schlix => Schlixf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "schlix");
   private static Icon? Screenpalf;
   public static Icon Screenpal => Screenpalf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "screenpal");
   private static Icon? Scribdf;
   public static Icon Scribd => Scribdf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "scribd");
   private static Icon? Searchenginf;
   public static Icon Searchengin => Searchenginf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "searchengin");
   private static Icon? Sellcastf;
   public static Icon Sellcast => Sellcastf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "sellcast");
   private static Icon? Sellsyf;
   public static Icon Sellsy => Sellsyf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "sellsy");
   private static Icon? Servicestackf;
   public static Icon Servicestack => Servicestackf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "servicestack");
   private static Icon? Shirtsinbulkf;
   public static Icon Shirtsinbulk => Shirtsinbulkf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "shirtsinbulk");
   private static Icon? Shoelacef;
   public static Icon Shoelace => Shoelacef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "shoelace");
   private static Icon? Shopifyf;
   public static Icon Shopify => Shopifyf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "shopify");
   private static Icon? Shopwaref;
   public static Icon Shopware => Shopwaref ??= new Icon(IconFamily.Classic, IconStyle.Brands, "shopware");
   private static Icon? SignalMessengerf;
   public static Icon SignalMessenger => SignalMessengerf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "signal-messenger");
   private static Icon? Simplybuiltf;
   public static Icon Simplybuilt => Simplybuiltf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "simplybuilt");
   private static Icon? Sistrixf;
   public static Icon Sistrix => Sistrixf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "sistrix");
   private static Icon? Sithf;
   public static Icon Sith => Sithf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "sith");
   private static Icon? Sitroxf;
   public static Icon Sitrox => Sitroxf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "sitrox");
   private static Icon? Sketchf;
   public static Icon Sketch => Sketchf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "sketch");
   private static Icon? Skyatlasf;
   public static Icon Skyatlas => Skyatlasf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "skyatlas");
   private static Icon? Skypef;
   public static Icon Skype => Skypef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "skype");
   private static Icon? Slackf;
   public static Icon Slack => Slackf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "slack");
   public static Icon SlackHash => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.Slack;
   private static Icon? Slidesharef;
   public static Icon Slideshare => Slidesharef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "slideshare");
   private static Icon? Snapchatf;
   public static Icon Snapchat => Snapchatf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "snapchat");
   public static Icon SnapchatGhost => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.Snapchat;
   private static Icon? Soundcloudf;
   public static Icon Soundcloud => Soundcloudf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "soundcloud");
   private static Icon? Sourcetreef;
   public static Icon Sourcetree => Sourcetreef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "sourcetree");
   private static Icon? SpaceAwesomef;
   public static Icon SpaceAwesome => SpaceAwesomef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "space-awesome");
   private static Icon? Speakapf;
   public static Icon Speakap => Speakapf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "speakap");
   private static Icon? SpeakerDeckf;
   public static Icon SpeakerDeck => SpeakerDeckf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "speaker-deck");
   private static Icon? Spotifyf;
   public static Icon Spotify => Spotifyf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "spotify");
   private static Icon? SquareBehancef;
   public static Icon SquareBehance => SquareBehancef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-behance");
   public static Icon BehanceSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareBehance;
   private static Icon? SquareDribbblef;
   public static Icon SquareDribbble => SquareDribbblef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-dribbble");
   public static Icon DribbbleSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareDribbble;
   private static Icon? SquareFacebookf;
   public static Icon SquareFacebook => SquareFacebookf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-facebook");
   public static Icon FacebookSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareFacebook;
   private static Icon? SquareFontAwesomef;
   public static Icon SquareFontAwesome => SquareFontAwesomef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-font-awesome");
   private static Icon? SquareFontAwesomeStrokef;
   public static Icon SquareFontAwesomeStroke => SquareFontAwesomeStrokef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-font-awesome-stroke");
   public static Icon FontAwesomeAlt => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareFontAwesomeStroke;
   private static Icon? SquareGitf;
   public static Icon SquareGit => SquareGitf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-git");
   public static Icon GitSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareGit;
   private static Icon? SquareGithubf;
   public static Icon SquareGithub => SquareGithubf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-github");
   public static Icon GithubSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareGithub;
   private static Icon? SquareGitlabf;
   public static Icon SquareGitlab => SquareGitlabf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-gitlab");
   public static Icon GitlabSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareGitlab;
   private static Icon? SquareGooglePlusf;
   public static Icon SquareGooglePlus => SquareGooglePlusf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-google-plus");
   public static Icon GooglePlusSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareGooglePlus;
   private static Icon? SquareHackerNewsf;
   public static Icon SquareHackerNews => SquareHackerNewsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-hacker-news");
   public static Icon HackerNewsSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareHackerNews;
   private static Icon? SquareInstagramf;
   public static Icon SquareInstagram => SquareInstagramf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-instagram");
   public static Icon InstagramSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareInstagram;
   private static Icon? SquareJsf;
   public static Icon SquareJs => SquareJsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-js");
   public static Icon JsSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareJs;
   private static Icon? SquareLastfmf;
   public static Icon SquareLastfm => SquareLastfmf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-lastfm");
   public static Icon LastfmSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareLastfm;
   private static Icon? SquareLetterboxdf;
   public static Icon SquareLetterboxd => SquareLetterboxdf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-letterboxd");
   private static Icon? SquareOdnoklassnikif;
   public static Icon SquareOdnoklassniki => SquareOdnoklassnikif ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-odnoklassniki");
   public static Icon OdnoklassnikiSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareOdnoklassniki;
   private static Icon? SquarePiedPiperf;
   public static Icon SquarePiedPiper => SquarePiedPiperf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-pied-piper");
   public static Icon PiedPiperSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquarePiedPiper;
   private static Icon? SquarePinterestf;
   public static Icon SquarePinterest => SquarePinterestf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-pinterest");
   public static Icon PinterestSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquarePinterest;
   private static Icon? SquareRedditf;
   public static Icon SquareReddit => SquareRedditf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-reddit");
   public static Icon RedditSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareReddit;
   private static Icon? SquareSnapchatf;
   public static Icon SquareSnapchat => SquareSnapchatf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-snapchat");
   public static Icon SnapchatSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareSnapchat;
   private static Icon? SquareSteamf;
   public static Icon SquareSteam => SquareSteamf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-steam");
   public static Icon SteamSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareSteam;
   private static Icon? SquareThreadsf;
   public static Icon SquareThreads => SquareThreadsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-threads");
   private static Icon? SquareTumblrf;
   public static Icon SquareTumblr => SquareTumblrf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-tumblr");
   public static Icon TumblrSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareTumblr;
   private static Icon? SquareTwitterf;
   public static Icon SquareTwitter => SquareTwitterf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-twitter");
   public static Icon TwitterSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareTwitter;
   private static Icon? SquareViadeof;
   public static Icon SquareViadeo => SquareViadeof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-viadeo");
   public static Icon ViadeoSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareViadeo;
   private static Icon? SquareVimeof;
   public static Icon SquareVimeo => SquareVimeof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-vimeo");
   public static Icon VimeoSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareVimeo;
   private static Icon? SquareWhatsappf;
   public static Icon SquareWhatsapp => SquareWhatsappf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-whatsapp");
   public static Icon WhatsappSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareWhatsapp;
   private static Icon? SquareXTwitterf;
   public static Icon SquareXTwitter => SquareXTwitterf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-x-twitter");
   private static Icon? SquareXingf;
   public static Icon SquareXing => SquareXingf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-xing");
   public static Icon XingSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareXing;
   private static Icon? SquareYoutubef;
   public static Icon SquareYoutube => SquareYoutubef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "square-youtube");
   public static Icon YoutubeSquare => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.SquareYoutube;
   private static Icon? Squarespacef;
   public static Icon Squarespace => Squarespacef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "squarespace");
   private static Icon? StackExchangef;
   public static Icon StackExchange => StackExchangef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "stack-exchange");
   private static Icon? StackOverflowf;
   public static Icon StackOverflow => StackOverflowf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "stack-overflow");
   private static Icon? Stackpathf;
   public static Icon Stackpath => Stackpathf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "stackpath");
   private static Icon? Staylinkedf;
   public static Icon Staylinked => Staylinkedf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "staylinked");
   private static Icon? Steamf;
   public static Icon Steam => Steamf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "steam");
   private static Icon? SteamSymbolf;
   public static Icon SteamSymbol => SteamSymbolf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "steam-symbol");
   private static Icon? StickerMulef;
   public static Icon StickerMule => StickerMulef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "sticker-mule");
   private static Icon? Stravaf;
   public static Icon Strava => Stravaf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "strava");
   private static Icon? Stripef;
   public static Icon Stripe => Stripef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "stripe");
   private static Icon? StripeSf;
   public static Icon StripeS => StripeSf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "stripe-s");
   private static Icon? Stubberf;
   public static Icon Stubber => Stubberf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "stubber");
   private static Icon? Studiovinarif;
   public static Icon Studiovinari => Studiovinarif ??= new Icon(IconFamily.Classic, IconStyle.Brands, "studiovinari");
   private static Icon? Stumbleuponf;
   public static Icon Stumbleupon => Stumbleuponf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "stumbleupon");
   private static Icon? StumbleuponCirclef;
   public static Icon StumbleuponCircle => StumbleuponCirclef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "stumbleupon-circle");
   private static Icon? Superpowersf;
   public static Icon Superpowers => Superpowersf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "superpowers");
   private static Icon? Supplef;
   public static Icon Supple => Supplef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "supple");
   private static Icon? Susef;
   public static Icon Suse => Susef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "suse");
   private static Icon? Swiftf;
   public static Icon Swift => Swiftf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "swift");
   private static Icon? Symfonyf;
   public static Icon Symfony => Symfonyf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "symfony");
   private static Icon? Teamspeakf;
   public static Icon Teamspeak => Teamspeakf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "teamspeak");
   private static Icon? Telegramf;
   public static Icon Telegram => Telegramf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "telegram");
   public static Icon TelegramPlane => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.Telegram;
   private static Icon? TencentWeibof;
   public static Icon TencentWeibo => TencentWeibof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "tencent-weibo");
   private static Icon? TheRedYetif;
   public static Icon TheRedYeti => TheRedYetif ??= new Icon(IconFamily.Classic, IconStyle.Brands, "the-red-yeti");
   private static Icon? Themecof;
   public static Icon Themeco => Themecof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "themeco");
   private static Icon? Themeislef;
   public static Icon Themeisle => Themeislef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "themeisle");
   private static Icon? ThinkPeaksf;
   public static Icon ThinkPeaks => ThinkPeaksf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "think-peaks");
   private static Icon? Threadsf;
   public static Icon Threads => Threadsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "threads");
   private static Icon? Tiktokf;
   public static Icon Tiktok => Tiktokf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "tiktok");
   private static Icon? TradeFederationf;
   public static Icon TradeFederation => TradeFederationf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "trade-federation");
   private static Icon? Trellof;
   public static Icon Trello => Trellof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "trello");
   private static Icon? Tumblrf;
   public static Icon Tumblr => Tumblrf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "tumblr");
   private static Icon? Twitchf;
   public static Icon Twitch => Twitchf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "twitch");
   private static Icon? Twitterf;
   public static Icon Twitter => Twitterf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "twitter");
   private static Icon? Typo3f;
   public static Icon Typo3 => Typo3f ??= new Icon(IconFamily.Classic, IconStyle.Brands, "typo3");
   private static Icon? Uberf;
   public static Icon Uber => Uberf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "uber");
   private static Icon? Ubuntuf;
   public static Icon Ubuntu => Ubuntuf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "ubuntu");
   private static Icon? Uikitf;
   public static Icon Uikit => Uikitf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "uikit");
   private static Icon? Umbracof;
   public static Icon Umbraco => Umbracof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "umbraco");
   private static Icon? Unchartedf;
   public static Icon Uncharted => Unchartedf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "uncharted");
   private static Icon? Uniregistryf;
   public static Icon Uniregistry => Uniregistryf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "uniregistry");
   private static Icon? Unityf;
   public static Icon Unity => Unityf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "unity");
   private static Icon? Unsplashf;
   public static Icon Unsplash => Unsplashf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "unsplash");
   private static Icon? Untappdf;
   public static Icon Untappd => Untappdf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "untappd");
   private static Icon? Upsf;
   public static Icon Ups => Upsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "ups");
   private static Icon? Upworkf;
   public static Icon Upwork => Upworkf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "upwork");
   private static Icon? Usbf;
   public static Icon Usb => Usbf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "usb");
   private static Icon? Uspsf;
   public static Icon Usps => Uspsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "usps");
   private static Icon? Ussunnahf;
   public static Icon Ussunnah => Ussunnahf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "ussunnah");
   private static Icon? Vaadinf;
   public static Icon Vaadin => Vaadinf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "vaadin");
   private static Icon? Viacoinf;
   public static Icon Viacoin => Viacoinf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "viacoin");
   private static Icon? Viadeof;
   public static Icon Viadeo => Viadeof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "viadeo");
   private static Icon? Viberf;
   public static Icon Viber => Viberf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "viber");
   private static Icon? Vimeof;
   public static Icon Vimeo => Vimeof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "vimeo");
   private static Icon? VimeoVf;
   public static Icon VimeoV => VimeoVf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "vimeo-v");
   private static Icon? Vinef;
   public static Icon Vine => Vinef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "vine");
   private static Icon? Vkf;
   public static Icon Vk => Vkf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "vk");
   private static Icon? Vnvf;
   public static Icon Vnv => Vnvf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "vnv");
   private static Icon? Vuejsf;
   public static Icon Vuejs => Vuejsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "vuejs");
   private static Icon? WatchmanMonitoringf;
   public static Icon WatchmanMonitoring => WatchmanMonitoringf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "watchman-monitoring");
   private static Icon? Wazef;
   public static Icon Waze => Wazef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "waze");
   private static Icon? Webflowf;
   public static Icon Webflow => Webflowf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "webflow");
   private static Icon? Weeblyf;
   public static Icon Weebly => Weeblyf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "weebly");
   private static Icon? Weibof;
   public static Icon Weibo => Weibof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "weibo");
   private static Icon? Weixinf;
   public static Icon Weixin => Weixinf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "weixin");
   private static Icon? Whatsappf;
   public static Icon Whatsapp => Whatsappf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "whatsapp");
   private static Icon? Whmcsf;
   public static Icon Whmcs => Whmcsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "whmcs");
   private static Icon? WikipediaWf;
   public static Icon WikipediaW => WikipediaWf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wikipedia-w");
   private static Icon? Windowsf;
   public static Icon Windows => Windowsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "windows");
   private static Icon? Wirsindhandwerkf;
   public static Icon Wirsindhandwerk => Wirsindhandwerkf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wirsindhandwerk");
   public static Icon Wsh => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.Wirsindhandwerk;
   private static Icon? Wixf;
   public static Icon Wix => Wixf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wix");
   private static Icon? WizardsOfTheCoastf;
   public static Icon WizardsOfTheCoast => WizardsOfTheCoastf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wizards-of-the-coast");
   private static Icon? Woduf;
   public static Icon Wodu => Woduf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wodu");
   private static Icon? WolfPackBattalionf;
   public static Icon WolfPackBattalion => WolfPackBattalionf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wolf-pack-battalion");
   private static Icon? Wordpressf;
   public static Icon Wordpress => Wordpressf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wordpress");
   private static Icon? WordpressSimplef;
   public static Icon WordpressSimple => WordpressSimplef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wordpress-simple");
   private static Icon? Wpbeginnerf;
   public static Icon Wpbeginner => Wpbeginnerf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wpbeginner");
   private static Icon? Wpexplorerf;
   public static Icon Wpexplorer => Wpexplorerf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wpexplorer");
   private static Icon? Wpformsf;
   public static Icon Wpforms => Wpformsf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wpforms");
   private static Icon? Wpressrf;
   public static Icon Wpressr => Wpressrf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "wpressr");
   public static Icon Rendact => global::Rocket.Surgery.Blazor.FontAwesome6.Pro.FaBrands.Wpressr;
   private static Icon? XTwitterf;
   public static Icon XTwitter => XTwitterf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "x-twitter");
   private static Icon? Xboxf;
   public static Icon Xbox => Xboxf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "xbox");
   private static Icon? Xingf;
   public static Icon Xing => Xingf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "xing");
   private static Icon? YCombinatorf;
   public static Icon YCombinator => YCombinatorf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "y-combinator");
   private static Icon? Yahoof;
   public static Icon Yahoo => Yahoof ??= new Icon(IconFamily.Classic, IconStyle.Brands, "yahoo");
   private static Icon? Yammerf;
   public static Icon Yammer => Yammerf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "yammer");
   private static Icon? Yandexf;
   public static Icon Yandex => Yandexf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "yandex");
   private static Icon? YandexInternationalf;
   public static Icon YandexInternational => YandexInternationalf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "yandex-international");
   private static Icon? Yarnf;
   public static Icon Yarn => Yarnf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "yarn");
   private static Icon? Yelpf;
   public static Icon Yelp => Yelpf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "yelp");
   private static Icon? Yoastf;
   public static Icon Yoast => Yoastf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "yoast");
   private static Icon? Youtubef;
   public static Icon Youtube => Youtubef ??= new Icon(IconFamily.Classic, IconStyle.Brands, "youtube");
   private static Icon? Zhihuf;
   public static Icon Zhihu => Zhihuf ??= new Icon(IconFamily.Classic, IconStyle.Brands, "zhihu");
}
