name: Close Milestone
on:
  release:
    types:
      - released
jobs:
  close_milestone:
    uses: RocketSurgeonsGuild/actions/.github/workflows/close-milestone6.yml@v0.3.10
    secrets:
      RSG_BOT_TOKEN: ${{ secrets.RSG_BOT_TOKEN }}
