name: Create Milestone and Draft Release
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: '0 0 * * 4'
jobs:
  create_milestone_and_draft_release:
    uses: RocketSurgeonsGuild/actions/.github/workflows/draft-release.yml@v0.2.6
    secrets:
      RSG_BOT_TOKEN: ${{ secrets.RSG_BOT_TOKEN }}
