name: Nukeeper Update

on:
  repository_dispatch:
    types: [nukeeper]

defaults:
  run:
    shell: pwsh
jobs:
  nukeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: install nukeeper
        run: |
          dotnet tool install -g nukeeper

      - name: nukeeper repo
        run: |
          nukeeper repo https://github.com/${{ github.repository }} ${{ secrets.RSG_BOT_TOKEN }}
