name: Update Milestone
on:
  pull_request_target:
    types:
      - closed
      - opened
      - reopened
      - synchronize

jobs:
  update_milestone:
    uses: RocketSurgeonsGuild/actions/.github/workflows/update-milestone.yml@v0.2.5
